### ISSUE TITLE
Changing order of IMGUI on top

### ISSUE THREAD

**Issue by EssenWorkbench** [mrjbom/VulkanDemo#1]
How to change the dependency and then making the IMGUI on top of the texture ?

**Comment by mrjbom** [comment]
I don't quite understand what "making the IMGUI on top of the texture" means

**Comment by EssenWorkbench** [comment]
Current version is rendering the IMGUI windows prior than the texture from
what you loaded file.
Z buffer concept wise, the texture is blocking the IMGUI window.
I'd like to to change the rendering order in order to make the hovering
operation of IMGUI with user operation, but I couldn't figure out it due to
lack of Vulkan knowledge.
I just started learning and I am going to figure out it, but if you can
help me, I would really appreciate it.

Regards;
SeongNam.

**Comment by mrjbom** [comment]
Now I think I understand what you mean. At the moment, my application draws the texture first, and then imgui, the imgui window is always on top of the texture. I use two subpasses in one renderpass. You can see how they are organized in the createRenderPass() function. If you are familiar with how renderpass works, then I think you will understand. Ask if you don't understand something.

**Comment by EssenWorkbench** [comment]
Actually, the texture is on top of imgui and it is different behavior
against my expectation and your explanation.

Then, I was trying to find the reason, but I couldn't find it due to lack
of vulkan knowledge to me yet.

**Comment by mrjbom** [comment]
Download the application version from the releases page, launch the application and try to move the imgui window to a rotating square, you will see that imgui is drawn on top of it, as it should be. If this is not the case, then send a screenshot.

**Comment by EssenWorkbench** [comment]
The latest version is working fine.

Inside the void MainWindow::cleanupSwapchain() function, there is a typo :
Current : for (VkImage& imageView : swapchainImageViews)
To be : for (VkImageView& imageView : swapchainImageViews)

**Comment by mrjbom** [comment]
There really is a typo. A typo was also to blame for the original problem. Thank you for noticing her.
If you have any questions, you can write and I will be happy to help.
